name: build-mobile-ui

on:
  push:
    paths:
      - 'packages/ui/**'
  pull_request:
    paths:
      - 'packages/ui/**'

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Build packages/ui
        run: pnpm -C packages/ui run build
      - name: List built files
        run: ls -la packages/ui/dist || true
